from __future__ import annotations

def count_tokens(text: str) -> int: ...
def count_tokens_for_model(text: str, model: str) -> int: ...
def count_message_tokens(messages: list[dict[str, str]]) -> int: ...
def get_context_window_size(model: str) -> int: ...
