from __future__ import annotations

from typing import Any

class GuardrailChain:
    def __init__(self) -> None: ...
    def add_content_moderation(
        self,
        block_patterns: list[str] | None = None,
        warn_patterns: list[str] | None = None,
    ) -> GuardrailChain: ...
    def add_pii_detection(self, action: str = "redact") -> GuardrailChain: ...
    def add_token_limit(
        self,
        max_input: int | None = None,
        max_output: int | None = None,
    ) -> GuardrailChain: ...
    def add_regex_filter(
        self,
        block_rules: list[str] | None = None,
        warn_rules: list[str] | None = None,
    ) -> GuardrailChain: ...
    def add_schema(self, schema: dict[str, Any]) -> GuardrailChain: ...
    def list(self) -> list[str]: ...
    def destroy(self) -> None: ...
