from __future__ import annotations

from typing import Any

class ApprovalManager:
    def __init__(self) -> None: ...
    def request(
        self, tool_name: str, args: dict[str, Any], session_id: str
    ) -> str: ...
    def approve(
        self, request_id: str, modified_args: dict[str, Any] | None = None
    ) -> None: ...
    def deny(self, request_id: str, reason: str | None = None) -> None: ...
    def list_pending(self) -> list[dict[str, Any]]: ...
    def destroy(self) -> None: ...

class CheckpointStore:
    def __init__(self) -> None: ...
    async def save(self, checkpoint: dict[str, Any]) -> None: ...
    async def load(self, checkpoint_id: str) -> dict[str, Any]: ...
    def destroy(self) -> None: ...
