from __future__ import annotations

from typing import Any

class McpServer:
    def __init__(self, name: str, version: str) -> None: ...
    def add_tool(self, tool: dict[str, Any]) -> McpServer: ...
    async def handle(self, message: dict[str, Any]) -> dict[str, Any]: ...
    def destroy(self) -> None: ...
