from __future__ import annotations

from typing import Any

class Memory:
    def __init__(self) -> None: ...
    async def store(self, entry: dict[str, Any]) -> None: ...
    async def recall(
        self,
        session_id: str | None = None,
        query: str | None = None,
        limit: int = 10,
    ) -> list[dict[str, Any]]: ...
    async def clear(self, session_id: str | None = None) -> None: ...
    def destroy(self) -> None: ...
