from __future__ import annotations

from typing import Any

class PluginRegistry:
    def __init__(self) -> None: ...
    def add_telemetry(self) -> PluginRegistry: ...
    def add_memory(self) -> PluginRegistry: ...
    def list(self) -> list[str]: ...
    def emit(self, event: dict[str, Any]) -> None: ...
    def destroy(self) -> None: ...
