from __future__ import annotations

from typing import Any

class Telemetry:
    def __init__(self) -> None: ...
    def record_span(self, span: dict[str, Any]) -> None: ...
    def export_spans(self) -> list[dict[str, Any]]: ...
    def export_metrics(self) -> dict[str, Any]: ...
    def clear(self) -> None: ...
    def destroy(self) -> None: ...
