from __future__ import annotations

from typing import Any

class ToolValidator:
    def __init__(self, strategies: list[str] | None = None) -> None: ...
    def validate(self, input_data: Any, schema: dict[str, Any]) -> Any: ...
    def destroy(self) -> None: ...
