from __future__ import annotations

from typing import Any

class VectorStore:
    def __init__(self) -> None: ...
    async def upsert(self, chunks: list[dict[str, Any]]) -> None: ...
    async def search(
        self, query_embedding: list[float], top_k: int = 10
    ) -> list[dict[str, Any]]: ...
    def destroy(self) -> None: ...

def cosine_similarity(a: list[float], b: list[float]) -> float: ...
