/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Linux musl support (simplified)
  return false
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = true
        try {
          nativeBinding = require('./gauss-napi.darwin-x64.node')
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = true
        try {
          nativeBinding = require('./gauss-napi.darwin-arm64.node')
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        localFileExisted = true
        try {
          if (isMusl()) {
            nativeBinding = require('./gauss-napi.linux-x64-musl.node')
          } else {
            nativeBinding = require('./gauss-napi.linux-x64-gnu.node')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = true
        try {
          if (isMusl()) {
            nativeBinding = require('./gauss-napi.linux-arm64-musl.node')
          } else {
            nativeBinding = require('./gauss-napi.linux-arm64-gnu.node')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = true
        try {
          nativeBinding = require('./gauss-napi.win32-x64-msvc.node')
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

// NAPI-RS exports camelCase by default. The SDK and index.d.ts use snake_case.
// Export both conventions for compatibility.
const binding = { ...nativeBinding }
for (const key of Object.keys(nativeBinding)) {
  const snakeKey = key.replace(/([A-Z])/g, '_$1').toLowerCase()
  if (snakeKey !== key) {
    binding[snakeKey] = nativeBinding[key]
  }
}

module.exports = binding
